module.exports = [
  {
    sectionKey: "header",
    sectionName: "Header",
    order: 0,
    button: {
      text: "Get a Quote",
      link: "#contact",
    },
    items: [
      { label: "About", link: "#about" },
      { label: "Services", link: "#services" },
      { label: "Projects", link: "#projects" },
      { label: "Process", link: "#process" },
      { label: "Contact", link: "#contact" },
    ],
    settings: {
      logo: "",
      phone: "+1 (000) 000-0000",
      email: "hello@example.com",
    },
  },
  {
    sectionKey: "hero",
    sectionName: "Hero",
    order: 1,
    title: "Building spaces that last",
    subtitle: "Commercial and residential construction",
    description: "Disciplined construction for offices, homes, and mixed-use developments.",
    image: "",
    button: {
      text: "Start a project",
      link: "#contact",
    },
  },
  {
    sectionKey: "about",
    sectionName: "About",
    order: 2,
    title: "A builder focused on the long term",
    subtitle: "About the company",
    description:
      "We plan carefully, build cleanly, and stay accountable from the first site visit through handover.",
    image: "",
    button: {
      text: "Our process",
      link: "#process",
    },
    items: [
      { title: "Years", value: "25+", description: "Delivering commercial and residential work." },
      { title: "Projects", value: "180+", description: "Completed across the region." },
      { title: "Trades", value: "40+", description: "Coordinated under one site team." },
    ],
  },
  {
    sectionKey: "services",
    sectionName: "Services",
    order: 3,
    title: "Full-spectrum construction",
    description: "Professional construction services.",
    items: [
      {
        number: "01",
        title: "Commercial Construction",
        description: "Offices, retail, and mixed-use buildings.",
        image: "/uploads/commercial.jpg",
      },
      {
        number: "02",
        title: "Residential Construction",
        description: "Professional residential construction.",
        image: "/uploads/residential.jpg",
      },
      {
        number: "03",
        title: "Renovation",
        description: "Structural and interior renovations with occupied-site care.",
        image: "",
      },
    ],
  },
  {
    sectionKey: "projects",
    sectionName: "Projects",
    order: 4,
    title: "Selected work",
    description: "A sample of recently completed buildings.",
    items: [
      {
        title: "Harbor House",
        category: "Residential",
        description: "A four-storey residential building delivered on a tight urban site.",
        image: "",
        link: "",
      },
      {
        title: "North Exchange",
        category: "Commercial",
        description: "Office and retail space built for a mixed-use block.",
        image: "",
        link: "",
      },
    ],
  },
  {
    sectionKey: "why-us",
    sectionName: "Why Us",
    order: 5,
    title: "Why teams hire us",
    description: "Clear scope, a steady site, and a finish that matches the drawings.",
    items: [
      {
        icon: "plan",
        title: "Documented scope",
        description: "Budgets and schedules are written down before work starts.",
      },
      {
        icon: "site",
        title: "One site lead",
        description: "Trades, inspections, and client updates run through a single lead.",
      },
      {
        icon: "quality",
        title: "Finish standards",
        description: "Handover includes a punch list, manuals, and as-built notes.",
      },
    ],
  },
  {
    sectionKey: "process",
    sectionName: "Process",
    order: 6,
    title: "How a project moves",
    description: "Four stages from the first call to handover.",
    items: [
      { number: "01", title: "Consult", description: "Walk the site, confirm the brief, and flag constraints." },
      { number: "02", title: "Plan", description: "Lock scope, budget, schedule, and procurement." },
      { number: "03", title: "Build", description: "Run the site with weekly progress and cost updates." },
      { number: "04", title: "Handover", description: "Complete inspections, punch list, and closeout documents." },
    ],
  },
  {
    sectionKey: "testimonials",
    sectionName: "Testimonials",
    order: 7,
    title: "Client notes",
    description: "Feedback from recent project owners.",
    items: [
      {
        name: "John Doe",
        position: "CEO",
        company: "ABC Company",
        message: "Excellent service. The team kept the schedule visible and the site orderly.",
        image: "/uploads/john.jpg",
      },
      {
        name: "Amira Shah",
        position: "Development Manager",
        company: "North Exchange",
        message: "Clear communication from demolition through handover.",
        image: "",
      },
    ],
  },
  {
    sectionKey: "cta",
    sectionName: "CTA",
    order: 8,
    title: "Planning a build?",
    subtitle: "Tell us about the site",
    description: "Share the location, timeline, and what you want built. We will reply with the next step.",
    image: "",
    button: {
      text: "Request a consultation",
      link: "#contact",
    },
  },
  {
    sectionKey: "contact",
    sectionName: "Contact",
    order: 9,
    title: "Contact",
    description: "Call, email, or send a note about your project.",
    settings: {
      email: "hello@example.com",
      phone: "+1 (000) 000-0000",
      address: "100 Builder Street",
      hours: "Monday to Friday, 8:00 to 17:00",
      mapUrl: "",
    },
    items: [
      { label: "Projects desk", value: "hello@example.com", type: "email" },
      { label: "Site line", value: "+1 (000) 000-0000", type: "phone" },
    ],
  },
  {
    sectionKey: "footer",
    sectionName: "Footer",
    order: 10,
    description: "Commercial and residential construction.",
    items: [
      { group: "Explore", label: "Services", link: "#services" },
      { group: "Explore", label: "Projects", link: "#projects" },
      { group: "Company", label: "About", link: "#about" },
      { group: "Company", label: "Contact", link: "#contact" },
    ],
    settings: {
      logo: "",
      copyright: "All rights reserved.",
    },
  },
];
